#!/usr/bin/python3

import csv
import sys
import traceback
from calc import *


def str_to_nb(strtab):
    return [int(value) for value in strtab]


try:
    if len(sys.argv) < 2:
        exit(84)
    with open('207demography_data.csv', newline='') as csvfile:
        reader = csv.reader(csvfile, delimiter=';')
        data = [row for row in reader]
        years = [int(x) for x in data[0][2:]]
        rows = list(filter(lambda x: x[1] in sys.argv, data))
        countries = [x[0] for x in rows]
        values = [str_to_nb(x[2:]) for x in rows]
        do_calc(countries, years, values)
except Exception as e:
    print(traceback.format_exc())
    exit(84)

