#!/usr/bin/python3

import csv
import sys

try:
    if len(sys.argv) < 2:
        exit(84)
    with open('207demography_data.csv', newline='') as csvfile:
        reader = csv.reader(csvfile, delimiter=';')
        data = [row for row in reader]
        countries = list(filter(lambda x: x[1] in sys.argv, data))
        print(countries)
except Exception as e:
    print(e)
    exit(84)
